# Generated by Django 5.2.5 on 2025-09-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(blank=True, max_length=240, verbose_name='Resumo (subtítulo)')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Capa (opcional)')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
