# Generated by Django 5.2.5 on 2025-09-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
