# Generated by Django 5.2.5 on 2025-09-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userpost_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='core/avatars/avatar1.png', max_length=120),
        ),
    ]
